name: 'gradle'
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'orb/**'
      - 'scan/**'
      - 'vsts/**'
      - 'common/**'
      - 'action.yaml'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'tsconfig.base.json'
      - '.github/workflows/node.yml'
  push:
    branches:
      - main
      - 'releases/*'
    paths-ignore:
      - 'orb/**'
      - 'scan/**'
      - 'vsts/**'
      - 'common/**'
      - 'action.yaml'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'tsconfig.base.json'
      - '.github/workflows/node.yml'
permissions:
  # Allows the EndBug/add-and-commit step to commit the package manager changes,
  # adding the AppMap language library and configuration file appmap.yml.
  # Once the EndBug/add-and-commit is removed, this permission can be removed, 
  # unless you need it for other reasons.
  contents: write

  # Allows the getappmap/archive-action to write a PR comment with the 
  # AppMap configuration status.
  pull-requests: write
jobs:
  gradleValidation:
    name: gradle-wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.1.0

  gradle-test:
    name: gradle-test
    needs: gradleValidation
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        gradleVersion:
          - 6.8
          - 6.9.2
          - 7.6.2
          - 8.3
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 11
          cache: gradle
      # Begin AppMap CI language agent installation.
      # This snippet can be safely removed once the AppMap language agent has been
      # added to the project dependencies, and appmap.yml has been created.
      - name: Install AppMap tools
        id: install-appmap
        uses: getappmap/install-action@v1
        with:
          project-type: gradle
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "ci: Add AppMap language agent and appmap.yml"
      # End AppMap CI language agent installation
      - name: Run linters and test
        run: ./gradlew test -PtestGradleVersion="${{ matrix.gradleVersion }}"
      - name: Collect test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.gradleVersion }}-${{ runner.os }}
          path: ${{ github.workspace }}/build/reports/tests
