name: 'gradle'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
    paths-ignore:
      - 'orb/**'
      - 'scan/**'
      - 'vsts/**'
      - 'common/**'
      - 'action.yaml'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'tsconfig.base.json'
      - '.github/workflows/node.yml'
  schedule:
    - cron: '0 0 * * 0'
jobs:
  gradleValidation:
    name: gradle-wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.1.0

  gradle-test:
    name: gradle-test
    needs: gradleValidation
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        gradleVersion:
          - 6.8
          - 6.9.2
          - 7.6.2
          - 8.3
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 11
          cache: gradle
      - name: Run tests
        run: ./gradlew appmap test -PtestGradleVersion="${{ matrix.gradleVersion }}"
      - name: Save AppMaps
        uses: actions/cache/save@v3
        if: always()
        with:
          path: ./tmp/appmap
          key: appmaps-${{ github.sha }}-${{ github.run_attempt }}
      - name: Collect test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.gradleVersion }}-${{ runner.os }}
          path: ${{ github.workspace }}/build/reports/tests
          
  appmap-analysis:
    if: always()
    needs: [ gradle-test ]
    uses: getappmap/analyze-action/.github/workflows/appmap-analysis.yml@v1
    permissions:
      actions: read
      contents: read
      checks: write
      pull-requests: write